###
get http://localhost:8888/api/puppies

###
get http://localhost:8888/api/ceremony

###
get http://localhost:8888/api/couple

###
get http://localhost:8888/api/engagement

###
get http://localhost:8888/api/getting-ready

###
get http://localhost:8888/api/family

###
get http://localhost:8888/api/reception

###
get http://localhost:8888/api/videos

###
get http://localhost:8888/api/home